# Generated by Django 5.1.4 on 2025-03-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("workbooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="workbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workbooks.workbook"
            ),
        ),
    ]
