# Generated by Django 5.1.4 on 2025-03-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("workbooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="workbook",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workbooks.workbook",
            ),
        ),
    ]
