# Generated by Django 5.1 on 2025-03-24 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbooks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="answer",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="question",
        ),
        migrations.AddField(
            model_name="quiz",
            name="question",
            field=models.ManyToManyField(to="workbooks.question"),
        ),
    ]
