# Generated by Django 5.1 on 2025-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbooks", "0002_remove_quiz_answer_alter_quiz_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="question",
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ManyToManyField(to="workbooks.question"),
        ),
    ]
