# Generated by Django 5.1 on 2025-04-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workbooks", "0003_remove_answer_question_answer_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="workbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quizzes",
                to="workbooks.workbook",
            ),
        ),
    ]
